### ISSUE TITLE
ui: enhancements

### ISSUE THREAD

**Issue by tusharnankani** [HarshKapadia2/git-graph#20]
Let's start.

0. `backdrop-filter: blur(4px);` ez hehe.

![image](https://user-images.githubusercontent.com/61280281/162823325-d193034a-29c2-4d87-aa59-521ee8a5d3d9.png)

![image](https://user-images.githubusercontent.com/61280281/162825785-e1ff2c92-8038-4b68-baeb-d525d0fe5f98.png)

Low-effort pretty eh?

1. Why are the buttons displacing on click? 

https://user-images.githubusercontent.com/61280281/162825295-830e7ae4-4cc3-4137-a9d5-31a6e47d45e2.mp4

I understand the effect you want to create. 
But essentially movement/displacement of elements is not preferred. Why do you think `CLS` is part of the lighthouse score? Why do you think `marquee` tag is obsolete?
I vaguely remember Kartik telling me once; how it is not a good practice if elements are displaced/moved on interaction. 

Sleek transitions are alright, but maybe not this?
Why? Because if you see the video again, the `div` is moving, not the `cross-icon`. 

I will give a simple example. Let's say you have a transition where the `underline-offset` goes from `4px` to `2px` on hover, so you will change the underline offset right? You do not bring the text closer to the underline and change the `line-height` or `translateY()` 💀

When we say transition: you can play around with shadows, blurs, and opacities to give effects, not directly to the parent body. 

2. From the 0th effect^ we get the blur effect, however for object content, why don't we add a differentiating factor, like extra blue, since that part can be scrollable based on the content size. 

https://user-images.githubusercontent.com/61280281/162827206-b00b68d3-bfc3-4c3f-909d-6e60b474a059.mp4

Right, now it is like this because we had a common class.

![image](https://user-images.githubusercontent.com/61280281/162826379-0560587c-e277-42fa-805f-d5e0f2cd1cb6.png)

But you get the point right. 

![image](https://user-images.githubusercontent.com/61280281/162826414-9ce9ff19-43e9-4b54-a2f6-3fb61b73698f.png)

**Comment by HarshKapadia2** [comment]
Thank you for the suggestions @tusharnankani!

### Points 0 and 2

I've made the changes you mentioned in points 0 and 2 and modified them to my taste in commits 478d91c3f2fcb61c632687aee970418ed6bc79ff and 8f88633b7a583ba947cba843e16ccf170b342861. Good suggestions! Thank you!

### Point 1

> Why are the buttons displacing on click?

That's the default behaviour of buttons and I didn't think it was necessary to change that, because that user feedback is good.

> But essentially movement/displacement of elements is not preferred. Why do you think `CLS` is part of the lighthouse score? Why do you think `marquee` tag is obsolete?
> I vaguely remember Kartik telling me once; how it is not a good practice if elements are displaced/moved on interaction.

- The Web Vital 'CLS' measures layout shift, not minute in-place displacement of elements.
	- An example of a large CLS value, which is bad: Multiple `div`s rendered on page load causing the page content to 'jump'.
- Also, this default behaviour of buttons is for user feedback, which is required for a good UX. It does not affect CLS at all.
- Just FYI, some [disadvantages of the `marquee` tag](https://stackoverflow.com/questions/4855252/disadvantages-of-marquee-tag). I couldn't find the official reasons for making it obsolete, maybe because it was never a HTML standard.
- So, the point is that extreme movements and displacements are not good. This one does not come under that.

> Sleek transitions are alright, but maybe not this?
> Why? Because if you see the video again, the `div` is moving, not the `cross-icon`.

I do not see the issue with this movement.

> I will give a simple example. Let's say you have a transition where the underline-offset goes from `4px` to `2px` on hover, so you will change the underline offset right? You do not bring the text closer to the underline and change the `line-height` or `translateY()` 💀

The current button 'issue' is not this bad in my opinion.

**Comment by tusharnankani** [comment]
> So, the point is that extreme movements and displacements are not good. This one does not come under that.

Got it, understood. 

> > Sleek transitions are alright, but maybe not this?
Why? Because if you see the video again, the div is moving, not the cross-icon.
>
> I do not see the issue with this movement.

Maybe I do not like the original style of a button. In fact, initially, I thought you made such an effect, because I always reset my button styles, that I did not remember this is what the OG button looks like. 

Sleek transitions are alright, but maybe not this?
Why? Because if you see the video again, the div is moving, not the cross-icon.

> I do not see the issue with this movement.

You are right, our opinions is just based on our preferences.


Thanks for the clarification, I appreciate you! <3
